[package]
name = "jojo"
version = "0.1.4"
authors = ["Xie Yuheng <xyheme@gmail.com>"]
edition = "2018"
description = "JOJO's Bizarre Programming Adventure."
license = "GPL-3.0"

[dependencies]
dic = "0.1.4"