#!/usr/bin/env bash

# c="g++"
c="clang++"

tangle () {
    ./tangle.js
}

build ()
{
    tangle
    f="-Wall -Wno-infinite-recursion"
    time $c $f jojo.cpp -o jojo
}

release () {
    tangle
    f="-Wall -Wno-infinite-recursion -foptimize-sibling-calls -O2"
    time $c $f jojo.cpp -o jojo
}

clean () {
    rm -f jojo
}

testing () {
    tangle
    clean
    build
    time ./jojo
}

debug () {
    tangle
    clean
    build
    time valgrind ./jojo
    # time valgrind --leak-check=full ./jojo
}

install () {
    cp jojo ~/bin/
}

default () {
    $@
}

default $@
